# Generated by Django 4.2.2 on 2023-06-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='phone',
        ),
    ]
